Repository taylorjohnson141/rancid-tomatillos, pull requests merged in 2020-10, with the labels that each got.

#14 Movies component tj
  src/App.js
  src/Movies.js
Labels: JavaScript, Movies, React, iteration1

#16 Movie component styling tj
  src/App.css
  src/App.js
  src/Movies.js
Labels: CSS, Movies

#18 Import Login, assign to onClick for login-button
  src/Header.js
Labels: Login, React, iteration 2

#19 Login component tj
  src/Login.js
Labels: Login, React, iteration 2

#20 Login showing tj
  src/App.js
  src/Header.js
  src/Login.js
Labels: React, iteration 2

#21 Fix login tj
  src/App.js
  src/Header.js
  src/Login.js
Labels: iteration 2

#22 Create handle submit method
  src/Login.js
Labels: iteration 2

#23 Css cd
  package-lock.json
  package.json
  src/App.css
  src/Header.js
  src/Login.js
Labels: CSS, dom

#24 Fix arctitecture tj
  src/App.js
  src/Login.js
  src/Movies.js
Labels: fetch, iteration 2

#25 Change views on clicks cd
  src/App.css
  src/App.js
  src/Header.js
  src/Login.js
  src/Logout.js
Labels: CSS, HTML, Login, React, dom

#27 Show single movie
  src/Movie.js
  src/Movies.js
Labels: fetch, iteration 3

#31 Rating fetch tj
  src/App.js
  src/Header.js
  src/Movies.js
Labels: fetch, iteration 4

#32 Header testing cd
  src/Header.js
  src/Header.test.js
Labels: header, iteration1, testing

#42 Router cd
  package-lock.json
  package.json
  src/App.js
  src/Header.js
  src/Home.js
  src/Login.js
  src/LoginButton.js
  src/Logout.js
  src/Movie.js
  src/Movies.js
  src/index.js
Labels: Login, React, architecture, enhancement, iteration 6, refactor, router

#44 Refactor router movie click tj
  src/App.js
  src/Header.js
  src/Home.js
  src/Login.js
  src/LoginButton.js
  src/LogoutButton.js
  src/Movie.js
  src/Movies.js
Labels: JavaScript, React, iteration 6, router

#45 Api Calls and Movie test cd
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/Header.js
  src/Login.js
  src/LoginButton.js
  src/LogoutButton.js
  src/Movie.js
  src/Movie.test.js
  src/Movies.js
  src/apiCalls.js
Labels: architecture, iteration 4, refactor, testing

#47 Header test refactor cd
  src/Header.test.js
  src/LogoutButton.js
  src/Movie.js
Labels: iteration 4, refactor, router, testing

#50 Login logout button tests cd
  src/Login.js
  src/Login.test.js
  src/LoginButton.js
  src/LoginButton.test.js
  src/LogoutButton.js
  src/LogoutButton.test.js
  src/Movie.test.js
Labels: React, iteration 4, testing
